[project]
name = "mediapipedemos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
